/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4NALDFopm0b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function loading() {
  return (
    <div className="flex items-center justify-center h-screen bg-primary">
      <div className="animate-spin rounded-full border-4 border-primary-foreground border-t-transparent h-12 w-12" />
    </div>
  )
}
